version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.7
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
    - 6.2.5
    - 6.2.7
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.2.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.19.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
